/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.gradle.api.Project
import org.gradle.api.Plugin
import org.gradle.configurationcache.extensions.capitalized
import org.gradle.jvm.tasks.Jar
import org.gradle.kotlin.dsl.attributes
import org.gradle.kotlin.dsl.get
import org.gradle.kotlin.dsl.getByName
import org.gradle.kotlin.dsl.named

/**
 * A simple 'hello world' plugin.
 */
class GradleBasePlugin : Plugin<Project> {
    override fun apply(project: Project) {
        project.tasks.named<Jar>("jar") {
            // https://docs.gradle.org/current/userguide/java_plugin.html#tab:configurations
            val main = listOf("compileClasspath", "runtimeClasspath")
            //            val test = listOf("testCompileClasspath", "testRuntimeClasspath")
            doFirst {
                manifest {
                    project.configurations.filter { it.name in main }.forEach { c ->
                        val name = "Dependencies-" + c.name.substringBefore("Classpath").capitalized()
                        val deps = c.resolvedConfiguration.resolvedArtifacts
                                .map { a -> a.moduleVersion.id.toString() + a.classifier?.let { ":$it" }.orEmpty() }
                                .sorted().joinToString(";")
                        attributes(name to deps)
                    }
                }
            }
        }
    }
}
