[common]
default-java-version = 8
repositories = ["scijava.public=https://maven.scijava.org/content/groups/public"]

[status]
rules = "rules.xml"
projects = "projects.txt"
badges = "ci-badges.txt"
timestamps = "timestamps.txt"
html = "index.html"
header = "header.html"
footer = "footer.html"

[melt]
java-version = 11
template = "tests/mega-melt-template.xml"
excludes = [
    # TEMP: Exclude org.bytedeco:hdf5 until cisd:jhdf5 is gone.
    'org.bytedeco:hdf5',
    # TEMP: Skip components within multi-module reactors.
    # Neither pombast nor release-version.sh understand multi-
    # module repositories; release-version.sh needs to learn how
    # to tag and release individual components from multi-module
    # repos, so that when pombast shallow clones the repo at that
    # tag and invokes a build, it will be building only the
    # released component as it does with single-component repos.
    'org.scijava:scijava-collections',
    'org.scijava:scijava-common3',
    'org.scijava:scijava-concurrent',
    'org.scijava:scijava-discovery-test',
    'org.scijava:scijava-discovery',
    'org.scijava:scijava-function',
    'org.scijava:scijava-legacy',
    'org.scijava:scijava-meta',
    'org.scijava:scijava-ops-api',
    'org.scijava:scijava-ops-benchmarks',
    'org.scijava:scijava-ops-engine',
    'org.scijava:scijava-ops-ext-parser',
    'org.scijava:scijava-ops-flim',
    'org.scijava:scijava-ops-image',
    'org.scijava:scijava-ops-indexer',
    'org.scijava:scijava-ops-opencv',
    'org.scijava:scijava-ops-spi',
    'org.scijava:scijava-ops-tutorial',
    'org.scijava:scijava-priority',
    'org.scijava:scijava-progress',
    'org.scijava:scijava-struct',
    'org.scijava:scijava-taglets',
    'org.scijava:scijava-testutil',
    'org.scijava:scijava-types',
    'mpicbg:mpicbg', 'mpicbg:mpicbg_',
    # NB: Skip artifacts requiring minimum Java version >11.
    'net.algart:algart-tiff',
    'org.openjfx:javafx-base',
    'org.openjfx:javafx-controls',
    'org.openjfx:javafx-fxml',
    'org.openjfx:javafx-graphics',
    'org.openjfx:javafx-media',
    'org.openjfx:javafx-swing',
    'org.openjfx:javafx-web',
    'org.morphonets:SNT',
    # NB: Skip closed-source artifacts.
    'org.bonej:bonej-plus',
    # NB: The following artifacts have messy dependency trees.
    # Too many problems to test as part of the mega-melt.
    # See WARNING block in pom-scijava's pom.xml for details.
    'net.imagej:imagej-server',
    'org.apache.spark:spark-core_2.11',
    # NB: Skip scijava forks of third-party projects.
    # These are very stable, with few/no dependencies, and
    # don't need to be retested as pom-scijava evolves.
    'org.scijava:j3dcore',
    'org.scijava:j3dutils',
    'org.scijava:jep',
    'org.scijava:junit-benchmarks',
    'org.scijava:vecmath',
    # NB: Skip alternate flavors of other managed components.
    'org.jogamp.gluegen:gluegen',     # uberjar flavor of gluegen-rt
    'org.jogamp.jogl:jogl-all-noawt', # slimmed down flavor of jogl-all
    # NB: All the SWT platform JARs have the same classes.
    # The current platform will be brought in transitively.
    'org.eclipse.swt:org.eclipse.swt.cocoa.macosx',
    'org.eclipse.swt:org.eclipse.swt.cocoa.macosx.x86_64',
    'org.eclipse.swt:org.eclipse.swt.gtk.aix.ppc',
    'org.eclipse.swt:org.eclipse.swt.gtk.aix.ppc64',
    'org.eclipse.swt:org.eclipse.swt.gtk.hpux.ia64',
    'org.eclipse.swt:org.eclipse.swt.gtk.linux.ppc',
    'org.eclipse.swt:org.eclipse.swt.gtk.linux.ppc64',
    'org.eclipse.swt:org.eclipse.swt.gtk.linux.s390',
    'org.eclipse.swt:org.eclipse.swt.gtk.linux.s390x',
    'org.eclipse.swt:org.eclipse.swt.gtk.linux.x86',
    'org.eclipse.swt:org.eclipse.swt.gtk.linux.x86_64',
    'org.eclipse.swt:org.eclipse.swt.gtk.solaris.sparc',
    'org.eclipse.swt:org.eclipse.swt.gtk.solaris.x86',
    'org.eclipse.swt:org.eclipse.swt.win32.win32.x86',
    'org.eclipse.swt:org.eclipse.swt.win32.win32.x86_64',
    # NB: All SLF4J bindings have the same classes.
    # We'll rely on logback-classic being present here.
    'org.slf4j:slf4j-jcl',
    'org.slf4j:slf4j-jdk14',
    'org.slf4j:slf4j-nop',
    'org.slf4j:slf4j-simple',
    # NB: Cannot include both commons-logging and jcl-over-slf4j;
    # see: http://www.slf4j.org/codes.html#jclDelegationLoop
    'org.slf4j:jcl-over-slf4j',
]

[smelt]
includes = [
    "ca.mcgill:*",
    "io.scif:*",
    "jitk:*",
    "mpicbg:*",
    "net.imagej:*",
    "net.imglib2:*",
    "net.preibisch:*",
    "org.bonej:*",
    "org.janelia.saalfeldlab:*",
    "org.janelia:*",
    "org.morphonets:*",
    "org.scijava:*",
    "sc.fiji:*",
]
excludes = [
  # NB: Skip closed-source artifacts.
  'org.bonej:bonej-plus',
  # NB: Skip scijava forks of third-party projects.
  # These are very stable, with few/no dependencies, and
  # don't need to be retested as pom-scijava evolves.
  'org.scijava:j3dcore',
  'org.scijava:j3dutils',
  'org.scijava:jep',
  'org.scijava:junit-benchmarks',
  'org.scijava:vecmath',
  # TEMP: Skip components within multi-module reactors.
  # Neither pombast nor release-version.sh understand multi-
  # module repositories; release-version.sh needs to learn how
  # to tag and release individual components from multi-module
  # repos, so that when pombast shallow clones the repo at that
  # tag and invokes a build, it will be building only the
  # released component as it does with single-component repos.
  'org.scijava:scijava-collections',
  'org.scijava:scijava-common3',
  'org.scijava:scijava-concurrent',
  'org.scijava:scijava-discovery-test',
  'org.scijava:scijava-discovery',
  'org.scijava:scijava-function',
  'org.scijava:scijava-legacy',
  'org.scijava:scijava-meta',
  'org.scijava:scijava-ops-api',
  'org.scijava:scijava-ops-benchmarks',
  'org.scijava:scijava-ops-engine',
  'org.scijava:scijava-ops-ext-parser',
  'org.scijava:scijava-ops-flim',
  'org.scijava:scijava-ops-image',
  'org.scijava:scijava-ops-indexer',
  'org.scijava:scijava-ops-opencv',
  'org.scijava:scijava-ops-spi',
  'org.scijava:scijava-ops-tutorial',
  'org.scijava:scijava-priority',
  'org.scijava:scijava-progress',
  'org.scijava:scijava-struct',
  'org.scijava:scijava-taglets',
  'org.scijava:scijava-testutil',
  'org.scijava:scijava-types',
]
skip-tests = [
    # java.lang.AssertionError
    #     at org.scijava.minimaven.BasicTest.testClassifiers(BasicTest.java:216)
    "org.scijava:minimaven",

    # Error while checking the CLIJ2 installation: null
    "sc.fiji:labkit-pixel-classification",
]

[remove-tests]

# CachedOpEnvironmentTest fails intermittently. Of course, it should be
# somehow fixed in imagej-ops. But for now, let's not let it ruin the melt.
"net.imagej:imagej-ops" = ["net.imagej.ops.cached.CachedOpEnvironmentTest"]

# In org.janelia.saalfeldlab.n5.metadata.ome.ngff.v04.WriteAxesTests.testXYT:
# java.util.NoSuchElementException: No value present
"org.janelia.saalfeldlab:n5-ij" = ["org.janelia.saalfeldlab.n5.metadata.ome.ngff.v04.WriteAxesTests"]

# Avoid notNull assertion error at
# org.janelia.saalfeldlab.n5.universe.metadata.MetadataTests.testEmptyBase(MetadataTests.java:346)
"org.janelia.saalfeldlab:n5-universe" = ["org.janelia.saalfeldlab.n5.universe.metadata.MetadataTests"]

# In org.janelia.saalfeldlab.n5.zarr.ZarrCachedFSTest.cacheBehaviorTest:
# arrays first differed at element [0]; expected:<[a]> but was:<[c]>
"org.janelia.saalfeldlab:n5-zarr" = ["org.janelia.saalfeldlab.n5.zarr.ZarrCachedFSTest"]
# Note: The above test is fixed with saalfeldlab/n5-zarr@e7edcec3,
# but the fix is only available in n5-zarr 2.0.0-alpha-1, and we
# do not want to update the SciJava BOM to the alpha version.

# In sc.fiji.labkit.ui.plugin.CalculateProbabilityMapWithLabkitIJ1PluginTest.test:
# Macro Error: "probability map for blobs.tif" not found in line 4
# selectImage ( <"probability map for blobs.tif"> ) ;
# java.lang.RuntimeException: Macro canceled
#     at ij.macro.Interpreter.error(Interpreter.java:1403)
#     at ij.macro.Functions.selectImage(Functions.java:3225)
#     at ij.macro.Functions.doFunction(Functions.java:136)
#     at ij.macro.Interpreter.doStatement(Interpreter.java:280)
#     at ij.macro.Interpreter.doStatements(Interpreter.java:266)
#     at ij.macro.Interpreter.run(Interpreter.java:162)
#     at ij.macro.Interpreter.run(Interpreter.java:92)
#     at sc.fiji.labkit.ui.plugin.CalculateProbabilityMapWithLabkitIJ1PluginTest.test(CalculateProbabilityMapWithLabkitIJ1PluginTest.java:65)
"sc.fiji:labkit-ui" = ["sc.fiji.labkit.ui.plugin.CalculateProbabilityMapWithLabkitIJ1PluginTest"]

[components."net.imagej:ij"]
java-version = 11

[components."net.imglib2:imglib2-mesh"]
java-version = 11
