/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.2/userguide/multi_project_builds.html
 */

rootProject.name = "gradle-platform"

dependencyResolutionManagement {

    //    repositories { .. }
    versionCatalogs {
//        create("libs") {
//            from("org.scijava:gradle-catalog:0.11")
//            library("my-lib", "com.mycompany:mylib:1.2")
//        }
//        maybeCreate("libs").version("groovy", "3.0.9")
//        maybeCreate("libs").library("groovy-core", "org.codehaus.groovy:groovy:2.4.15")

        // fails with "Could not resolve all artifacts for configuration 'incomingCatalogForLibs0'."
        create("libs").from(files("../catalog/build/version-catalog/libs.versions.toml"))
    }

    includeBuild("../catalog")
}

enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")