/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.2/userguide/multi_project_builds.html
 */

rootProject.name = "gradle-playground"

pluginManagement.repositories {
    gradlePluginPortal()
    maven("https://maven.scijava.org/content/repositories/releases")
}

dependencyResolutionManagement {

    //    repositories { .. }
    versionCatalogs {
        create("libs").from("org.scijava:gradle-catalog")

        // fails with "Could not resolve all artifacts for configuration 'incomingCatalogForLibs0'."
        //        create("libs").from(files("../catalog/build/version-catalog/libs.versions.toml"))
    }

    includeBuild("../catalog")
    //    includeBuild("../../../java-ecosystem-capabilities")
}

enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")